###
#Login to server
POST http://127.0.0.1:1080/login
Content-Type: application/json
Origin: http://foo.com'

{"username":"yan"}

###
#Update task status

PUT http://127.0.0.1:1080/task
Content-Type: application/json
Set-Cookie: insit=MTY1NzkwODE3NXxEdi1CQkFFQ180SUFBUkFCRUFBQVJ2LUNBQUlHYzNSeWFXNW5EQThBRFdGMWRHaGxiblJwWTJGMFpXUUVZbTl2YkFJQ0FBRUdjM1J5YVc1bkRBb0FDSFZ6WlhKdVlXMWxCbk4wY21sdVp3d0ZBQU41WVc0PXxau4oFbFuKFFSEk7NyDh2COpc0YmyqB1WkuNMXlEWmNQ==

{"description":"yan1","status": "done"}


###
#Create task

POST http://127.0.0.1:1080/task
Content-Type: application/json
Set-Cookie: cookie-name=MTY1NTIyMTQ2N3xEdi1CQkFFQ180SUFBUkFCRUFBQVJ2LUNBQUlHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dGQUFONVlXNEdjM1J5YVc1bkRBOEFEV0YxZEdobGJuUnBZMkYwWldRRVltOXZiQUlDQUFFPXxYeTIwGJ6lHgJCr60QRwnYGIFKmMCpJ8TunhhVpe85_Q==;

[{"description":"yan1","status": "open"},{"description":"yan2","status": "open"}]

###
#Get all tasks

GET http://127.0.0.1:1080/task
Content-Type: application/json
Set-Cookie: cookie-name=MTY1NTIyMTQ2N3xEdi1CQkFFQ180SUFBUkFCRUFBQVJ2LUNBQUlHYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dGQUFONVlXNEdjM1J5YVc1bkRBOEFEV0YxZEdobGJuUnBZMkYwWldRRVltOXZiQUlDQUFFPXxYeTIwGJ6lHgJCr60QRwnYGIFKmMCpJ8TunhhVpe85_Q==;

